sudo: true
dist: trusty
git:
  submodules: false # doesn't need 'em for tests
language: perl
perl:
  - "5.20"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - sudo apt-get -qq update
  - sudo apt-get install -y libreadline-dev
script:
  - prove -r t