sudo: true
dist: trusty
git:
  submodules: false # doesn't need 'em for tests
language: perl
perl:
  - "5.20"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libreadline-dev
  - cpanm -n https://github.com/kritikaio/devel-cover-report-kritika-perl/archive/master.tar.gz
script:
  - prove -r t && cover -test -report kritika